// <auto-generated />
using System;
using ECO.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECO.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608224720_ECO_Inicial")]
    partial class ECO_Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ECO.Dominio.Entidades.ECO_ColaSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMensaje")
                        .HasColumnType("Text")
                        .HasComment("Detalle de error de procasado de la solicitud.");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasComment("Estado del proceso de la solicitud. (0: Pendiente, 1: Procesando, 2: Exitosa, 3: Fallida).");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaUltimoIntento")
                        .HasColumnType("datetime");

                    b.Property<int>("Intentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Intentos del proceso");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasComment("Payload para la solicitud.");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Tipo de solicitud a realizar.");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("Tipo");

                    b.ToTable("ECO_ColaSolicitudes");
                });

            modelBuilder.Entity("ECO.Dominio.Entidades.ECO_Correo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Asunto del correo electrónico");

                    b.Property<string>("CorreoRespuesta")
                        .HasColumnType("varchar(150)")
                        .HasComment("Correo de respuesta (Reply-To).");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("Contenido del correo electrónico.");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int")
                        .HasComment("Empresa desde la cual se solicitó el envío de correo");

                    b.Property<string>("ErrorMensaje")
                        .HasColumnType("text")
                        .HasComment("Descripción del último error presentado durante el envío.");

                    b.Property<bool>("EsCuerpoHtml")
                        .HasColumnType("tinyint(1)")
                        .HasComment("Indica si el cuerpo del correo está en formato HTML.");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasComment("Estado actual del correo (Pendiente = 0, Enviado = 1, Fallido = 2).");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime")
                        .HasComment("Fecha y hora en que el correo fue enviado exitosamente.");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaCreado");

                    b.HasIndex("FechaEnvio");

                    b.ToTable("ECO_Correos");
                });

            modelBuilder.Entity("ECO.Dominio.Entidades.ECO_CorreoAdjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ContenidoArchivo")
                        .IsRequired()
                        .HasColumnType("longblob")
                        .HasComment("Contenido binario del archivo adjunto.");

                    b.Property<int>("CorreoId")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasComment("Extensión del archivo adjunto.");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("Nombre del archivo adjunto sin extensión.");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasComment("Tamaño del archivo en bytes.");

                    b.Property<string>("TipoContenido")
                        .HasColumnType("varchar(150)")
                        .HasComment("Tipo MIME del archivo adjunto.");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorreoId");

                    b.ToTable("ECO_CorreosAdjuntos");
                });

            modelBuilder.Entity("ECO.Dominio.Entidades.ECO_CorreoDestinatario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorreoId")
                        .HasColumnType("int");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasComment("Correo electrónico destinatario.");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasComment("Tipo de destinatario (Para = 0, CC = 1, CCO = 2).");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorreoId");

                    b.HasIndex("Destinatario");

                    b.HasIndex("Tipo");

                    b.ToTable("ECO_CorreosDestinatarios");
                });

            modelBuilder.Entity("ECO.Dominio.Entidades.ECO_CorreoEml", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ContenidoArchivo")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("CorreoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorreoId");

                    b.ToTable("ECO_CorreosEml");
                });

            modelBuilder.Entity("ECO.Dominio.Entidades.ECO_CorreoAdjunto", b =>
                {
                    b.HasOne("ECO.Dominio.Entidades.ECO_Correo", "Correo")
                        .WithMany("CorreosAdjuntos")
                        .HasForeignKey("CorreoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Correo");
                });

            modelBuilder.Entity("ECO.Dominio.Entidades.ECO_CorreoDestinatario", b =>
                {
                    b.HasOne("ECO.Dominio.Entidades.ECO_Correo", "Correo")
                        .WithMany("CorreosDestinatarios")
                        .HasForeignKey("CorreoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Correo");
                });

            modelBuilder.Entity("ECO.Dominio.Entidades.ECO_CorreoEml", b =>
                {
                    b.HasOne("ECO.Dominio.Entidades.ECO_Correo", "Correo")
                        .WithMany("CorreosEml")
                        .HasForeignKey("CorreoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Correo");
                });

            modelBuilder.Entity("ECO.Dominio.Entidades.ECO_Correo", b =>
                {
                    b.Navigation("CorreosAdjuntos");

                    b.Navigation("CorreosDestinatarios");

                    b.Navigation("CorreosEml");
                });
#pragma warning restore 612, 618
        }
    }
}
